[package]

name = "imap"
version = "0.0.3"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "MIT"

[dependencies]
openssl = "0.7.0"
regex = "0.1.41"
rand = "0.3.*"
